
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PortalDataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class TblAboutU
{

    public int AboutId { get; set; }

    public string AboutTitle { get; set; }

    public string AboutDescription { get; set; }

    public string AboutImageUrl { get; set; }

}

}
