
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PortalDataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class TblCategory
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TblCategory()
    {

        this.TblProducts = new HashSet<TblProduct>();

    }


    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public Nullable<bool> CategoryActive { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblProduct> TblProducts { get; set; }

}

}
