
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PortalDataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class TblCart
{

    public int CartId { get; set; }

    public Nullable<int> Quantity { get; set; }

    public Nullable<decimal> Price { get; set; }

    public int IsOrdered { get; set; }

    public Nullable<System.DateTime> DateTime { get; set; }

    public Nullable<int> ProductId { get; set; }

    public Nullable<int> UserId { get; set; }



    public virtual TblProduct TblProduct { get; set; }

    public virtual TblUser TblUser { get; set; }

}

}
