
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PortalDataLayer
{

using System;
    using System.Collections.Generic;
    
public partial class TblContact
{

    public int ContactId { get; set; }

    public string ContactName { get; set; }

    public string ContactMail { get; set; }

    public string ContactPhone { get; set; }

    public string ContactSubject { get; set; }

    public string ContactMessage { get; set; }

}

}
